In [65]:
import pandas as pd

In [66]:
import numpy as np

In [67]:
df=pd.read_csv('marital_status.csv')

In [68]:
df

age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   22     0.0
13   24     NaN
14   34     1.0
15   29     1.0
16   16     0.0
17   18     0.0
18   26     1.0
19   25     1.0

In [69]:
df.isnull().sum()

age       0
status    1
dtype: int64

In [70]:
handle=df['status'].median()

In [71]:
handle

0.0

In [72]:
df['status']=df['status'].fillna(handle)
df

age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   22     0.0
13   24     0.0
14   34     1.0
15   29     1.0
16   16     0.0
17   18     0.0
18   26     1.0
19   25     1.0

In [73]:
df_final.isnull().sum()   #from this line it is evident that 

0

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x=df[['age']]

In [76]:
y=df['status']

In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [78]:
x_train

age
7    30
15   29
11   20
19   25
10   26
4    17
13   24
6    23
16   16
3    28
2    24
8    29
9    22
5    33

In [79]:
x_test

age
18   26
14   34
1    33
17   18
0    21
12   22

In [80]:
y_train

7     0.0
15    1.0
11    0.0
19    1.0
10    1.0
4     0.0
13    0.0
6     0.0
16    0.0
3     1.0
2     0.0
8     1.0
9     0.0
5     1.0
Name: status, dtype: float64

In [81]:
y_test

18    1.0
14    1.0
1     1.0
17    0.0
0     0.0
12    0.0
Name: status, dtype: float64

In [82]:
from sklearn.linear_model import LogisticRegression

In [83]:
model=LogisticRegression()

In [84]:
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [85]:
model.predict(x_test)

array([0., 1., 1., 0., 0., 0.])

In [93]:
model.predict([[27]])  # We are trying to find out if the age is 27 what will be the status

array([1.])

In [94]:
model.score(x_test,y_test)  # Output of logistic regression 

0.8333333333333334

In [95]:
model.predict_proba(x_test)  # probability is tested on x_test data 

array([[0.50090875, 0.49909125],
       [0.02050128, 0.97949872],
       [0.03283799, 0.96716201],
       [0.9796442 , 0.0203558 ],
       [0.91852724, 0.08147276],
       [0.87421248, 0.12578752]])